{{- if .Values.workloads.managedNamespaces }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: anyscale-managed-namespaces
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  namespaces.yaml: |-
{{ toYaml .Values.workloads.managedNamespaces | indent 4 }}
{{- end }}
