{{- if and .Values.credentialMount.aws.enabled .Values.credentialMount.aws.createSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentialMount.aws.fromSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  credentials: {{ include "anyscale-operator.aws_credentials" . | b64enc | quote }}
  config: {{ include "anyscale-operator.aws_config" . | b64enc | quote }}
---
{{- end }}
{{- if and .Values.credentialMount.gcp.enabled .Values.credentialMount.gcp.createSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentialMount.gcp.fromSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  key.json: {{ required "credentialMount.gcp.createSecret.keyJsonB64 is required for GCP credential mount when credentialMount.gcp.createSecret.create is true" .Values.credentialMount.gcp.createSecret.keyJsonB64 | quote }}
{{- end }}
