apiVersion: v2
description: A Helm chart for Anyscale Operator
name: anyscale-operator
version: 1.2.0
dependencies:
- name: ingress-nginx
  version: "4.13.2"
  repository: "https://kubernetes.github.io/ingress-nginx"
  condition: ingress-nginx.enabled
